--  Eric Budd
--  CIT284
--  23 August 2017

--  BILLY MAYS HERE



--  #1

SELECT p.PRODUCTNAME, SUM(i.QUANTITY) AS QUANTITY
    FROM BB_PRODUCT p
    INNER JOIN BB_BASKETITEM i ON i.IDPRODUCT = P.IDPRODUCT
    INNER JOIN BB_BASKET b ON b.IDBASKET = i.IDBASKET
        WHERE b.ORDERPLACED = 1
            GROUP BY p.PRODUCTNAME
            ORDER BY QUANTITY DESC, p.PRODUCTNAME;


--  #2

SELECT s.LASTNAME, s.FIRSTNAME, SUM(i.QUANTITY) AS QUANTITY
    FROM BB_SHOPPER s, BB_BASKETITEM i
	INNER JOIN BB_BASKET b ON b.IDBASKET = i.IDBASKET
	INNER JOIN BB_PRODUCT p ON p.IDPRODUCT = i.IDPRODUCT
		WHERE b.ORDERPLACED = 1 AND p.PRODUCTNAME = 'Espresso'
			GROUP BY s.LASTNAME, s.FIRSTNAME
			ORDER BY s.LASTNAME, s.FIRSTNAME;


--  #3

SELECT m.MOVIE_TITLE, COUNT(r.MOVIE_ID) AS TIMES_RENTED
    FROM MM_MOVIE m
    INNER JOIN MM_RENTAL r ON r.MOVIE_ID = m.MOVIE_ID
    INNER JOIN MM_MOVIE_TYPE mt ON mt.MOVIE_CAT_ID = m.MOVIE_CAT_ID
        WHERE mt.MOVIE_CATEGORY = 'SciFi'
            GROUP BY m.MOVIE_TITLE;